### ISSUE TITLE
Feature request: static emoji for non-Nitro users

### ISSUE THREAD

**Issue by BassmanBiff** [PretzelCA/partydiscord#4]
In case anyone feels motivated to do this :)

**Comment by PretzelCA** [comment]
All the of the party parrots emojis are animated unfortunately.

**Comment by BassmanBiff** [comment]
I know, that's why I was requesting still frames that non-Nitro users can use :)

**Comment by PretzelCA** [comment]
Unfortunately, that's out of the project scope and something that should be suggested over at [jmhobbs/cultofthepartyparrot.com ](https://github.com/jmhobbs/cultofthepartyparrot.com)

I've gone ahead and made an issue about static versions of the Party Parrots
